/*
 * JS for Products generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '9c14b3b7-66ef-4b11-ba00-4c24d486bccf';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Scan",
    "location": "Scan.html"
}, {
    "name": "Products",
    "location": "Products.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Products_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelist_2': 'Products_mobilelist_2',
        'mobilelistitem_3': 'Products_mobilelistitem_3',
        'mobilelabel_9': 'Products_mobilelabel_9',
        'mobilelistitembutton_4': 'Products_mobilelistitembutton_4',
        'mobilelabel_10': 'Products_mobilelabel_10'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Products_list_service_onsuccess_mapping_0"] = {
        "homeScreen": "Products",
        "directions": [

        {
            "from_name": "list_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Products",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilelistitem_3']"

            },

            {

                "source": "$['body'][i]['Quantity']",
                "target": "$['mobilelistitem_3:counter_value']"

            },

            {

                "source": "$['body'][i]['Code']",
                "target": "$['mobilelistitem_3']['mobilelabel_10:text']"

            },

            {

                "source": "$['body'][i]['Name']",
                "target": "$['mobilelistitem_3']['mobilelabel_9:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Products_list_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Products",
        "directions": [

        {

            "to_name": "list_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.list_service = Apperyio.datasources.list_service = new Apperyio.DataSource(Warehouse_Product_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Products_list_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Products_list_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Products';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Products_onLoad = function() {
            Products_elementsExtraJS();

            Products_deviceEvents();
            Products_windowEvents();
            Products_elementsEvents();
        };

    // screen window events


    function Products_windowEvents() {

        $('#Products').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Products').on({
            pageshow: function(event) {
                try {
                    list_service.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function Products_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Products_elementsExtraJS() {
        // screen (Products) extra code

        /* mobilelist_2 */

        listView = $("#Products_mobilelist_2");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Products_mobilelist_2 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_3 */

    };

    // screen elements handler


    function Products_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Products").on("pagebeforeshow", "#Products", function(event, ui) {
        Apperyio.CurrentScreen = "Products";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Products_onLoad();
};

$(document).off("pagecreate", "#Products").on("pagecreate", "#Products", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Products_js();
});