/*
 * JS for Scan generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '9c14b3b7-66ef-4b11-ba00-4c24d486bccf';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Scan",
    "location": "Scan.html"
}, {
    "name": "Products",
    "location": "Products.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Scan_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'Scan_mobilebutton_2',
        'mobilebutton_3': 'Scan_mobilebutton_3',
        'name': 'Scan_name',
        'quantity': 'Scan_quantity',
        'barcode': 'Scan_barcode',
        'mobilebutton_7': 'Scan_mobilebutton_7'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Scan_mobilebarcode1_onsuccess_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [

        {
            "from_name": "mobilebarcode1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "productBarcode",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['text']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Scan_mobilebarcode1_onbeforesend_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": []
    };

    Apperyio.mappings["Scan_save_service_onsuccess_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": []
    };

    Apperyio.mappings["Scan_save_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [

        {
            "from_name": "Scan",
            "from_type": "UI",

            "to_name": "save_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['name:text']",
                "target": "$['parameters']['name']"

            },

            {

                "source": "$['quantity:text']",
                "target": "$['parameters']['quantity']"

            },

            {

                "source": "$['barcode:text']",
                "target": "$['parameters']['code']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Scan_search_service_onerror_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [

        {
            "from_name": "productBarcode",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Scan",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['barcode:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Scan_search_service_onsuccess_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [

        {
            "from_name": "search_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Scan",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['Quantity']",
                "target": "$['quantity:text']"

            },

            {

                "source": "$['body']['Code']",
                "target": "$['barcode:text']"

            },

            {

                "source": "$['body']['Name']",
                "target": "$['name:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Scan_search_service_onbeforesend_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [

        {
            "from_name": "productBarcode",
            "from_type": "LOCAL_STORAGE",

            "to_name": "search_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['code']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.mobilebarcode1 = Apperyio.datasources.mobilebarcode1 = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_mobilebarcode1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_mobilebarcode1_onsuccess_mapping_0"]);
            try {
                search_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.save_service = Apperyio.datasources.save_service = new Apperyio.DataSource(Warehouse_Product_save_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_save_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_save_service_onsuccess_mapping_0"]);
            Apperyio.navigateTo('Products', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.search_service = Apperyio.datasources.search_service = new Apperyio.DataSource(Warehouse_Product_search_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_search_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_search_service_onsuccess_mapping_0"]);
            alert("Product found in the warehouse\n and will be loaded for editing.");
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_search_service_onerror_mapping_0"]);
        }
    });

    Apperyio.CurrentScreen = 'Scan';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Scan_onLoad = function() {
            Scan_elementsExtraJS();

            Scan_deviceEvents();
            Scan_windowEvents();
            Scan_elementsEvents();
        };

    // screen window events


    function Scan_windowEvents() {

        $('#Scan').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Scan_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Scan_elementsExtraJS() {
        // screen (Scan) extra code

    };

    // screen elements handler


    function Scan_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Scan_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        mobilebarcode1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Scan_mobileheader [name="mobilebutton_2"]');
        $(document).off("click", '#Scan_mobileheader [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });

                }
            },
        }, '#Scan_mobileheader [name="mobilebutton_3"]');

        $(document).off("click", '#Scan_mobilecontainer [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        save_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Scan_mobilecontainer [name="mobilebutton_7"]');

    };

    $(document).off("pagebeforeshow", "#Scan").on("pagebeforeshow", "#Scan", function(event, ui) {
        Apperyio.CurrentScreen = "Scan";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Scan_onLoad();
};

$(document).off("pagecreate", "#Scan").on("pagecreate", "#Scan", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Scan_js();
});